INDICES = {
    "^GSPC": "S&P 500",
    "^DJI": "Dow Jones",
    "^IXIC": "NASDAQ Composite",
    "^RUT": "Russell 2000",
    "^FTSE": "FTSE 100",
    "^GDAXI": "DAX",
    "^FCHI": "CAC 40",
    "^N225": "Nikkei 225",
    "^HSI": "Hang Seng",
    "^AXJO": "ASX 200",
    "^STOXX50E": "Euro Stoxx 50",
    "^IBEX": "IBEX 35",
    "^OMX": "OMX Stockholm 30",
    "^BSESN": "BSE Sensex",
}

# Sector classifications for major stocks
SECTORS = {
    # Technology
    "AAPL": "Technology", "MSFT": "Technology", "GOOGL": "Technology", "GOOG": "Technology",
    "NVDA": "Technology", "META": "Technology", "TSLA": "Technology", "AVGO": "Technology",
    "ORCL": "Technology", "ADBE": "Technology", "CRM": "Technology", "CSCO": "Technology",
    "ACN": "Technology", "AMD": "Technology", "IBM": "Technology", "INTC": "Technology",
    "NOW": "Technology", "INTU": "Technology", "TXN": "Technology", "QCOM": "Technology",
    "AMAT": "Technology", "ADSK": "Technology", "PANW": "Technology", "PLTR": "Technology",
    "SNOW": "Technology", "ABNB": "Technology", "UBER": "Technology", "NFLX": "Technology",
    "SHOP": "Technology", "SQ": "Technology", "PYPL": "Technology", "V": "Technology",
    "MA": "Technology", "ADP": "Technology", "PAYX": "Technology", "FTNT": "Technology",
    "AKAM": "Technology", "ANET": "Technology", "CDNS": "Technology", "SNPS": "Technology",
    "KLAC": "Technology", "LRCX": "Technology", "NXPI": "Technology", "MCHP": "Technology",
    "ADI": "Technology", "APH": "Technology", "TEL": "Technology", "KEYS": "Technology",
    "ZBRA": "Technology", "ANSS": "Technology", "TYL": "Technology", "GDDY": "Technology",
    
    # Healthcare
    "UNH": "Healthcare", "JNJ": "Healthcare", "LLY": "Healthcare", "ABBV": "Healthcare",
    "MRK": "Healthcare", "TMO": "Healthcare", "ABT": "Healthcare", "DHR": "Healthcare",
    "PFE": "Healthcare", "AMGN": "Healthcare", "GILD": "Healthcare", "BMY": "Healthcare",
    "SYK": "Healthcare", "VRTX": "Healthcare", "MDT": "Healthcare", "ISRG": "Healthcare",
    "REGN": "Healthcare", "ELV": "Healthcare", "CI": "Healthcare", "HCA": "Healthcare",
    "CVS": "Healthcare", "ZTS": "Healthcare", "BDX": "Healthcare", "MCK": "Healthcare",
    "BSX": "Healthcare", "DXCM": "Healthcare", "IDXX": "Healthcare", "EW": "Healthcare",
    "RMD": "Healthcare", "BAX": "Healthcare", "A": "Healthcare", "ALGN": "Healthcare",
    "MRNA": "Healthcare", "IQV": "Healthcare", "BIIB": "Healthcare", "TECH": "Healthcare",
    "HOLX": "Healthcare", "PODD": "Healthcare", "RVTY": "Healthcare", "BIO": "Healthcare",
    
    # Finance
    "BRK.B": "Finance", "JPM": "Finance", "V": "Finance", "MA": "Finance",
    "BAC": "Finance", "WFC": "Finance", "MS": "Finance", "GS": "Finance",
    "AXP": "Finance", "BLK": "Finance", "SPGI": "Finance", "C": "Finance",
    "SCHW": "Finance", "CB": "Finance", "MMC": "Finance", "PGR": "Finance",
    "AON": "Finance", "CME": "Finance", "ICE": "Finance", "MCO": "Finance",
    "USB": "Finance", "TFC": "Finance", "PNC": "Finance", "BK": "Finance",
    "COF": "Finance", "AIG": "Finance", "MET": "Finance", "PRU": "Finance",
    "ALL": "Finance", "TRV": "Finance", "AJG": "Finance", "AFL": "Finance",
    "MSCI": "Finance", "NDAQ": "Finance", "TROW": "Finance", "BX": "Finance",
    "APO": "Finance", "IVZ": "Finance", "BEN": "Finance", "FITB": "Finance",
    "HBAN": "Finance", "RF": "Finance", "CFG": "Finance", "KEY": "Finance",
    
    # Consumer Discretionary
    "AMZN": "Consumer Discretionary", "TSLA": "Consumer Discretionary", "HD": "Consumer Discretionary",
    "MCD": "Consumer Discretionary", "NKE": "Consumer Discretionary", "SBUX": "Consumer Discretionary",
    "LOW": "Consumer Discretionary", "TJX": "Consumer Discretionary", "BKNG": "Consumer Discretionary",
    "CMG": "Consumer Discretionary", "MAR": "Consumer Discretionary", "ABNB": "Consumer Discretionary",
    "GM": "Consumer Discretionary", "F": "Consumer Discretionary", "ORLY": "Consumer Discretionary",
    "AZO": "Consumer Discretionary", "YUM": "Consumer Discretionary", "DPZ": "Consumer Discretionary",
    "LULU": "Consumer Discretionary", "POOL": "Consumer Discretionary", "BBY": "Consumer Discretionary",
    "DG": "Consumer Discretionary", "DLTR": "Consumer Discretionary", "ROST": "Consumer Discretionary",
    "TGT": "Consumer Discretionary", "TSCO": "Consumer Discretionary", "DHI": "Consumer Discretionary",
    "LEN": "Consumer Discretionary", "NVR": "Consumer Discretionary", "PHM": "Consumer Discretionary",
    
    # Consumer Staples
    "PG": "Consumer Staples", "KO": "Consumer Staples", "PEP": "Consumer Staples",
    "COST": "Consumer Staples", "WMT": "Consumer Staples", "MDLZ": "Consumer Staples",
    "PM": "Consumer Staples", "MO": "Consumer Staples", "CL": "Consumer Staples",
    "KMB": "Consumer Staples", "GIS": "Consumer Staples", "K": "Consumer Staples",
    "HSY": "Consumer Staples", "SYY": "Consumer Staples", "KHC": "Consumer Staples",
    "CAG": "Consumer Staples", "CPB": "Consumer Staples", "HRL": "Consumer Staples",
    "KR": "Consumer Staples", "SJM": "Consumer Staples", "MKC": "Consumer Staples",
    "TAP": "Consumer Staples", "STZ": "Consumer Staples", "TSN": "Consumer Staples",
    "EL": "Consumer Staples", "CLX": "Consumer Staples", "CHD": "Consumer Staples",
    
    # Energy
    "XOM": "Energy", "CVX": "Energy", "COP": "Energy", "SLB": "Energy",
    "EOG": "Energy", "MPC": "Energy", "PSX": "Energy", "VLO": "Energy",
    "OXY": "Energy", "HAL": "Energy", "DVN": "Energy", "FANG": "Energy",
    "BKR": "Energy", "APA": "Energy", "CTRA": "Energy", "MRO": "Energy",
    "EQT": "Energy", "WMB": "Energy", "OKE": "Energy", "KMI": "Energy",
    "TRGP": "Energy", "LNG": "Energy", "HES": "Energy",
    
    # Industrials
    "CAT": "Industrials", "BA": "Industrials", "GE": "Industrials", "RTX": "Industrials",
    "HON": "Industrials", "UPS": "Industrials", "LMT": "Industrials", "DE": "Industrials",
    "UNP": "Industrials", "MMM": "Industrials", "CSX": "Industrials", "NSC": "Industrials",
    "FDX": "Industrials", "EMR": "Industrials", "ETN": "Industrials", "ITW": "Industrials",
    "PH": "Industrials", "GD": "Industrials", "NOC": "Industrials", "LHX": "Industrials",
    "CARR": "Industrials", "OTIS": "Industrials", "PCAR": "Industrials", "CMI": "Industrials",
    "IR": "Industrials", "ROK": "Industrials", "DOV": "Industrials", "FTV": "Industrials",
    "FAST": "Industrials", "PAYX": "Industrials", "VRSK": "Industrials", "CPRT": "Industrials",
    
    # Utilities
    "NEE": "Utilities", "DUK": "Utilities", "SO": "Utilities", "D": "Utilities",
    "AEP": "Utilities", "EXC": "Utilities", "SRE": "Utilities", "XEL": "Utilities",
    "ED": "Utilities", "EIX": "Utilities", "WEC": "Utilities", "ES": "Utilities",
    "AWK": "Utilities", "DTE": "Utilities", "PPL": "Utilities", "AEE": "Utilities",
    "CMS": "Utilities", "CNP": "Utilities", "EVRG": "Utilities", "ETR": "Utilities",
    "FE": "Utilities", "ATO": "Utilities", "NI": "Utilities", "LNT": "Utilities",
    "PNW": "Utilities", "PEG": "Utilities", "CEG": "Utilities",
    
    # Real Estate
    "AMT": "Real Estate", "PLD": "Real Estate", "CCI": "Real Estate", "EQIX": "Real Estate",
    "PSA": "Real Estate", "WELL": "Real Estate", "DLR": "Real Estate", "O": "Real Estate",
    "SPG": "Real Estate", "SBAC": "Real Estate", "AVB": "Real Estate", "EQR": "Real Estate",
    "VTR": "Real Estate", "VICI": "Real Estate", "ESS": "Real Estate", "MAA": "Real Estate",
    "INVH": "Real Estate", "ARE": "Real Estate", "KIM": "Real Estate", "UDR": "Real Estate",
    "CPT": "Real Estate", "HST": "Real Estate", "REG": "Real Estate", "FRT": "Real Estate",
    
    # Materials
    "LIN": "Materials", "APD": "Materials", "SHW": "Materials", "FCX": "Materials",
    "NEM": "Materials", "ECL": "Materials", "DD": "Materials", "DOW": "Materials",
    "PPG": "Materials", "MLM": "Materials", "NUE": "Materials", "VMC": "Materials",
    "ALB": "Materials", "BALL": "Materials", "STLD": "Materials", "IP": "Materials",
    "PKG": "Materials", "EMN": "Materials", "MOS": "Materials", "FMC": "Materials",
    "CE": "Materials", "CF": "Materials", "IFF": "Materials", "LYB": "Materials",
    
    # Communication Services
    "GOOGL": "Communication Services", "GOOG": "Communication Services", "META": "Communication Services",
    "NFLX": "Communication Services", "DIS": "Communication Services", "CMCSA": "Communication Services",
    "T": "Communication Services", "VZ": "Communication Services", "TMUS": "Communication Services",
    "CHTR": "Communication Services", "EA": "Communication Services", "TTWO": "Communication Services",
    "LYV": "Communication Services", "NWSA": "Communication Services", "NWS": "Communication Services",
    "FOXA": "Communication Services", "FOX": "Communication Services", "OMC": "Communication Services",
    "IPG": "Communication Services", "MTCH": "Communication Services", "WBD": "Communication Services",
    
    # Indices (separate category so they never match with stocks)
    "^GSPC": "Index", "^DJI": "Index", "^IXIC": "Index", "^RUT": "Index",
    "^FTSE": "Index", "^GDAXI": "Index", "^FCHI": "Index", "^N225": "Index",
    "^HSI": "Index", "^AXJO": "Index", "^STOXX50E": "Index", "^IBEX": "Index",
    "^OMX": "Index", "^BSESN": "Index",
}

# Full S&P 500 constituent list (as of 2024)
SP500 = [
    "MMM",
    "AOS",
    "ABT",
    "ABBV",
    "ACN",
    "ADBE",
    "AMD",
    "AES",
    "AFL",
    "A",
    "APD",
    "ABNB",
    "AKAM",
    "ALB",
    "ARE",
    "ALGN",
    "ALLE",
    "LNT",
    "ALL",
    "GOOGL",
    "GOOG",
    "MO",
    "AMZN",
    "AMCR",
    "AEE",
    "AAL",
    "AEP",
    "AXP",
    "AIG",
    "AMT",
    "AWK",
    "AMP",
    "AME",
    "AMGN",
    "APH",
    "ADI",
    "ANSS",
    "AON",
    "APA",
    "APO",
    "AAPL",
    "AMAT",
    "APTV",
    "ACGL",
    "ADM",
    "ANET",
    "AJG",
    "AIZ",
    "T",
    "ATO",
    "ADSK",
    "ADP",
    "AZO",
    "AVB",
    "AVY",
    "AXON",
    "BKR",
    "BALL",
    "BAC",
    "BK",
    "BBWI",
    "BAX",
    "BDX",
    "BBY",
    "TECH",
    "BIO",
    "BIIB",
    "BLK",
    "BX",
    "BA",
    "BCH",
    "BSX",
    "BMY",
    "AVGO",
    "BR",
    "BRO",
    "BF.B",
    "BLDR",
    "BG",
    "CDNS",
    "CZR",
    "CPT",
    "CPB",
    "COF",
    "CAH",
    "KMX",
    "CCL",
    "CARR",
    "CTLT",
    "CAT",
    "CBOE",
    "CBRE",
    "CDW",
    "CE",
    "COR",
    "CNC",
    "CNP",
    "CF",
    "CHRW",
    "CRL",
    "SCHW",
    "CHTR",
    "CVX",
    "CMG",
    "CB",
    "CHD",
    "CI",
    "CINF",
    "CTAS",
    "CSCO",
    "C",
    "CFG",
    "CLX",
    "CME",
    "CMS",
    "KO",
    "CTSH",
    "CL",
    "CMCSA",
    "CMA",
    "CAG",
    "COP",
    "ED",
    "STZ",
    "CEG",
    "COO",
    "CPRT",
    "GLW",
    "CPAY",
    "CTVA",
    "CSGP",
    "COST",
    "CTRA",
    "CCI",
    "CSX",
    "CMI",
    "CVS",
    "DHI",
    "DHR",
    "DRI",
    "DVA",
    "DAY",
    "DECK",
    "DE",
    "DAL",
    "DVN",
    "DXCM",
    "FANG",
    "DLR",
    "DFS",
    "DG",
    "DLTR",
    "D",
    "DPZ",
    "DOV",
    "DOW",
    "DHR",
    "DTE",
    "DUK",
    "DD",
    "EMN",
    "ETN",
    "EBAY",
    "ECL",
    "EIX",
    "EW",
    "EA",
    "ELV",
    "LLY",
    "EMR",
    "ENPH",
    "ETR",
    "EOG",
    "EPAM",
    "EQT",
    "EFX",
    "EQIX",
    "EQR",
    "ESS",
    "EL",
    "ETSY",
    "EG",
    "EVRG",
    "ES",
    "EXC",
    "EXPE",
    "EXPD",
    "EXR",
    "XOM",
    "FFIV",
    "FDS",
    "FICO",
    "FAST",
    "FRT",
    "FDX",
    "FIS",
    "FITB",
    "FSLR",
    "FE",
    "FI",
    "FMC",
    "F",
    "FTNT",
    "FTV",
    "FOXA",
    "FOX",
    "BEN",
    "FCX",
    "GRMN",
    "IT",
    "GE",
    "GEHC",
    "GEV",
    "GEN",
    "GNRC",
    "GD",
    "GIS",
    "GPC",
    "GILD",
    "GPN",
    "GL",
    "GDDY",
    "GS",
    "HAL",
    "HIG",
    "HAS",
    "HCA",
    "DOC",
    "HSIC",
    "HSY",
    "HES",
    "HPE",
    "HLT",
    "HOLX",
    "HD",
    "HON",
    "HRL",
    "HST",
    "HWM",
    "HPQ",
    "HUBB",
    "HUM",
    "HBAN",
    "HII",
    "IBM",
    "IEX",
    "IDXX",
    "ITW",
    "INCY",
    "IR",
    "PODD",
    "INTC",
    "ICE",
    "IFF",
    "IP",
    "IPG",
    "INTU",
    "ISRG",
    "IVZ",
    "INVH",
    "IQV",
    "IRM",
    "JBHT",
    "JBL",
    "JKHY",
    "J",
    "JNJ",
    "JCI",
    "JPM",
    "JNPR",
    "K",
    "KVUE",
    "KDP",
    "KEY",
    "KEYS",
    "KMB",
    "KIM",
    "KMI",
    "KLAC",
    "KHC",
    "KR",
    "LHX",
    "LH",
    "LRCX",
    "LW",
    "LVS",
    "LDOS",
    "LEN",
    "LIN",
    "LYV",
    "LKQ",
    "LMT",
    "L",
    "LOW",
    "LULU",
    "LYB",
    "MTB",
    "MRO",
    "MPC",
    "MKTX",
    "MAR",
    "MMC",
    "MLM",
    "MAS",
    "MA",
    "MTCH",
    "MKC",
    "MCD",
    "MCK",
    "MDT",
    "MRK",
    "META",
    "MET",
    "MTD",
    "MGM",
    "MCHP",
    "MU",
    "MSFT",
    "MAA",
    "MRNA",
    "MHK",
    "MOH",
    "TAP",
    "MDLZ",
    "MPWR",
    "MNST",
    "MCO",
    "MS",
    "MOS",
    "MSI",
    "MSCI",
    "NDAQ",
    "NTAP",
    "NFLX",
    "NEM",
    "NWSA",
    "NWS",
    "NEE",
    "NKE",
    "NI",
    "NDSN",
    "NSC",
    "NTRS",
    "NOC",
    "NCLH",
    "NRG",
    "NUE",
    "NVDA",
    "NVR",
    "NXPI",
    "ORLY",
    "OXY",
    "ODFL",
    "OMC",
    "ON",
    "OKE",
    "ORCL",
    "OTIS",
    "PCAR",
    "PKG",
    "PLTR",
    "PH",
    "PAYX",
    "PAYC",
    "PYPL",
    "PNR",
    "PEP",
    "PFE",
    "PCG",
    "PM",
    "PSX",
    "PNW",
    "PNC",
    "POOL",
    "PPG",
    "PPL",
    "PFG",
    "PG",
    "PGR",
    "PLD",
    "PRU",
    "PEG",
    "PTC",
    "PSA",
    "PHM",
    "QRVO",
    "PWR",
    "QCOM",
    "DGX",
    "RL",
    "RJF",
    "RTX",
    "O",
    "REG",
    "REGN",
    "RF",
    "RSG",
    "RMD",
    "RVTY",
    "ROK",
    "ROL",
    "ROP",
    "ROST",
    "RCL",
    "SPGI",
    "CRM",
    "SBAC",
    "SLB",
    "STX",
    "SRE",
    "NOW",
    "SHW",
    "SPG",
    "SWKS",
    "SJM",
    "SW",
    "SNA",
    "SOLV",
    "SO",
    "LUV",
    "SWK",
    "SBUX",
    "STT",
    "STLD",
    "STE",
    "SYK",
    "SMCI",
    "SYF",
    "SNPS",
    "SYY",
    "TMUS",
    "TROW",
    "TTWO",
    "TPR",
    "TRGP",
    "TGT",
    "TEL",
    "TDY",
    "TFX",
    "TER",
    "TSLA",
    "TXN",
    "TXT",
    "TMO",
    "TJX",
    "TSCO",
    "TT",
    "TDG",
    "TRV",
    "TRMB",
    "TFC",
    "TYL",
    "TSN",
    "USB",
    "UBER",
    "UDR",
    "ULTA",
    "UNP",
    "UAL",
    "UPS",
    "URI",
    "UNH",
    "UHS",
    "VLO",
    "VTR",
    "VLTO",
    "VRSN",
    "VRSK",
    "VZ",
    "VRTX",
    "VTRS",
    "VICI",
    "V",
    "VMC",
    "WRB",
    "GWW",
    "WAB",
    "WBA",
    "WMT",
    "DIS",
    "WBD",
    "WM",
    "WAT",
    "WEC",
    "WFC",
    "WELL",
    "WST",
    "WDC",
    "WY",
    "WMB",
    "WTW",
    "WYNN",
    "XEL",
    "XYL",
    "YUM",
    "ZBRA",
    "ZBH",
    "ZTS",
]

ALL_TICKERS = {**INDICES, **{t: t for t in SP500}}